### ISSUE TITLE
[3pt] - Add comments counter - Student B

### ISSUE THREAD

**Issue by gdvl777** [eamador1/kaban#3]
Even if the API gives you the number of comments you will create a specific function to calculate it.

Make sure that the correct number is displayed on the Comments pop up.

Respect the following rules:

Each counter should be implemented as a separate module.
A counter function should look for specific DOM elements (e.g. for the comments counter it should look for comments) and make the counting based on what is actually displayed on the page.
A counter function should cover all the edge cases you can think about.

**Comment by V-Blaze** [comment]
Hi @gdvl777, @donice, @eamador1   

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![dcentl8-9b96e129-9725-401b-ac34-2feb990202a0](https://user-images.githubusercontent.com/107632780/229646232-19bbafea-ca96-4b36-ad5d-1d64c00d667c.gif)

## Invalid Code Review Request

## You have submitted a project, that doesn't meet the project requirement. You need to follow this [guideline](https://github.com/microverseinc/curriculum-tools-copy-projects) to create the kanban for your project. And also Your submission link should be a link to an issue that has the link to the Kanban board and a note informing the reviewer how many students are in your group.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
